26july countinuse auto slide feat
wix-incubator/pro-gallery pull request #416
Opened 2021-07-26 13:10 UTC by yakovhaiilo

2021-07-29 15:06 UTC, yhattav requested changes

2021-07-29 15:06 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +    isContinuesScrolling = false
continuous

2021-07-29 15:06 UTC, yhattav commented on packages/lib/test/defaultStyles.spec.js
> +    // autoSlideshowType: 'interval',
make sure this goes in the default and that the test is green

2021-07-29 15:06 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +    isContinuesScrolling = false
,

2021-07-29 15:06 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +      if (
if(cont) next....
else ("interval") next...

2021-07-29 15:06 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +        scrollDuration = styleParams.autoSlideshowContinuesSpeed;
!==
No speed needed in the function's arguments

2021-07-29 15:06 UTC, yhattav commented on packages/gallery/src/components/helpers/scrollHelper.js
> +  let change = to - from;
scrollingWidth

2021-07-29 15:06 UTC, yhattav commented on packages/gallery/src/components/helpers/scrollHelper.js
> +    duration = Math.abs(change) * duration;
change to speed
wrong calculation

2021-08-01 13:15 UTC, yhattav commented on packages/lib/src/common/coreStyles.js
> +  autoSlideshowContinuousSpeed: 2,
create a relevant number

2021-08-01 13:16 UTC, yhattav commented on packages/lib/test/defaultStyles.spec.js
> +    autoSlideshowContinuousSpeed: 2,
relevant default

2021-08-01 14:53 UTC, nirnaor commented
@yakovhaiilo  Isn't there a way to keep the scroll logic only inside `slideShowView`? and not in `galleryContainer`?

2021-08-02 07:51 UTC, yakovhaiilo commented
> @yakovhaiilo Isn't there a way to keep the scroll logic only inside `slideShowView`? and not in `galleryContainer`?

@nirnaor I see it is also called inside  ״galleryContainer״

2021-08-03 14:00 UTC, merged