update overlay design
wix-incubator/pro-gallery pull request #417
Opened 2021-07-26 15:45 UTC by yuvalab

2021-08-02 08:39 UTC, nirnaor requested changes

2021-08-02 08:39 UTC, nirnaor commented on packages/gallery/src/components/item/itemHover.js
> +    const { styleParams, imageDimensions } = this.props;
Remove calculations outside of the component. All these calculations are dependant on a few props (from the `styleParams`) therefor should not be performed inside a component that renders

2021-08-02 08:39 UTC, nirnaor commented on packages/gallery/src/components/item/itemHover.js
> +    marginTop += overlayPadding;
New code should be written [without mutations](https://github.com/immutable-js/immutable-js/#introduction).  This is out of scope for our meeting but still important

2021-08-02 08:39 UTC, nirnaor commented on packages/playground/src/constants/settings.js
> +    'overlayPosition',
Why can't we iterate over something inside lib instead of copying the new keys?

2021-08-10 12:34 UTC, nirnaor requested changes
let me know if you need help with the `const` thing.

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/src/components/item/itemHover.js
> +    console.log(width);
remove

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/src/components/item/itemHover.js
> +    let overlayHeight, overlayWidth, overlaySize;
can you try and make the entire method with `const` only? I want us to stop adding mutations to the code

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/src/components/item/itemHover.js
> +      display: 'flex',
Can you try without mutations?

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/tests/e2e/styleParams/overlayDesign.e2e.spec.js
> +    expect(page).toMatchImageSnapshot();
This code is duplicated :-( 
Makes it really hard to understand what is the difference between the tests.

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/tests/styleParams/overlayPosition.spec.js
> +    const overlaySizeImage = driver.find.selector('.gallery-item-hover').at(0);
can you reuse the logic ?

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/tests/styleParams/overlayPosition.spec.js
> +    console.log(overlaySizeImage.props().style);
remove debugging stuff

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/tests/styleParams/overlaySize.spec.js
> +    driver.mount.proGallery(initialProps);
duplicated

2021-08-10 12:34 UTC, nirnaor commented on packages/gallery/tests/styleParams/overlaySizeType.spec.js
> +      overlaySizeType: 'PERCENT',
duplicated

2021-08-10 12:40 UTC, IzaacAyelin commented on packages/gallery/src/components/item/itemHover.js
> +    console.log(width);
delete log

2021-08-12 10:20 UTC, merged