Cube fit position - new feature
wix-incubator/pro-gallery pull request #462
Opened 2021-08-05 08:18 UTC by guysopher

Align images in Grid Fit to different directions

2021-08-05 09:00 UTC, nirnaor approved these changes
I tried to avoid mutations in your changes but I think it's better to keep this file consistent

2021-08-05 10:12 UTC, IzaacAyelin reviewed
maybe we should add some e2es for the different options

2021-08-16 08:50 UTC, guysopher commented
@yhattav @IzaacAyelin can I merge this?

2021-08-16 08:59 UTC, nirnaor requested changes

2021-08-16 08:59 UTC, nirnaor commented on packages/gallery/tests/e2e/styleParams/cubeFitPosition.e2e.spec.js
> +    expect(page).toMatchImageSnapshot();
@guysopher This entire code is duplicated, makes it impossible to understand the difference between the tests.
Pleaes reuse the duplicated props and the logic parts:
```
    await driver.waitFor.hookToBeVisible('item-container');
    const page = await driver.grab.elemScreenshot('.pro-gallery');
    expect(page).toMatchImageSnapshot();
```

2021-08-16 09:02 UTC, nirnaor requested changes

2021-08-16 09:02 UTC, nirnaor commented on packages/gallery/tests/e2e/styleParams/cubeFitPosition.e2e.spec.js
> +    await driver.navigate({
All tests should look like this:
At the Top level please add:
```
const {TOP, RIGHT, LEFT, BOTTOM} = GALLERY_CONSTS.cubeFitPosition;
```

```
it('should align to the right', async () => {
    await driver.navigate(gridFitWithPosition(RIGHT),
    });
    await expectGalleryToMatchSnapshot()
  });
```

2021-08-22 11:08 UTC, IzaacAyelin commented
@nirnaor can this be mreged?

2021-08-24 09:08 UTC, nirnaor approved these changes

2021-08-24 09:08 UTC, nirnaor commented
> @nirnaor can this be merged?

yes. and sorry for the late response

2021-08-24 09:10 UTC, merged