improve accessibility helper func to work on ssr
wix-incubator/pro-gallery pull request #690
Opened 2021-12-28 12:10 UTC by yuvalab

2022-01-04 12:39 UTC, yhattav requested changes

2022-01-04 12:39 UTC, yhattav commented on packages/gallery/src/components/item/itemView.js
>        'text' : extractTextItemContent(this.props.html),
what happens when the text item is empty?

2022-01-04 12:39 UTC, yhattav commented on packages/gallery/src/components/item/itemView.js
>    getItemAriaLabel() {
why is this a function in the view element(react), can this move to galleryItem / itemsHelper?
in galleryItem we could have this as part of the calculatedAlt

2022-01-04 13:44 UTC, nirnaor approved these changes

2022-01-11 08:54 UTC, yhattav approved these changes

2022-01-11 09:26 UTC, merged