Bug fix scroll-less getMoreItems
wix-incubator/pro-gallery pull request #745
Opened 2022-02-09 18:03 UTC by yoavva

2022-02-09 18:15 UTC, yoavva commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +    this.initializeScrollPosition();
I just added the semicolon on this line

2022-02-10 07:44 UTC, yhattav requested changes
we said you'll talk to me before writing the PR...

2022-02-10 07:44 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +    const padding = 100; // Wix Platform adds padding to body height
who are Wix?

2022-02-10 07:44 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +      let nextHeight = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight);
when will const 103 be different than const 94?

2022-02-10 07:44 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +        await new Promise((res) => setTimeout(res, 100));
so just a slow while?

2022-02-24 08:48 UTC, yhattav requested changes

2022-02-24 08:48 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryHelpers.js
> +      this.reject = () => {
hey, there should be a fix here. this.reject(...args) =>{  reject(...args)} same with resolve
export class Deferred {
  constructor() {
    this.promise = new Promise((resolve, reject) => {
      this.reject = (...args) => {
        this.isPending = false;
        reject(...args);
      };
      this.resolve = (...args) => {
        this.isPending = false;
        resolve(...args);
      };
      this.isPending = true;
    });
  }
}

2022-02-24 12:40 UTC, yhattav approved these changes

2022-02-24 12:43 UTC, merged