use state to track scroll and check visiblity
wix-incubator/pro-gallery pull request #761
Opened 2022-03-02 19:53 UTC by IzaacAyelin

2022-03-03 12:14 UTC, nirnaor approved these changes

2022-03-03 12:14 UTC, nirnaor commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +  setScrollTop = (top) => {
@IzaacAyelin 
[suggestion]
if the method isn't reused elsewhere you can remove it

2022-03-07 13:20 UTC, yhattav requested changes

2022-03-07 13:20 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +      this.setScrollTop(top)
set scroll state. the scroll state is an object of {top, left}
Functions can use either one fut in these functions we must update on what happened. not what we want to use right now.

2022-03-07 13:20 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +        scrollTop: top,
setState ({scroll})
where 
scroll = {top,left}

2022-03-07 13:20 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +   const { container } = this.props;
why isnt this all part of a function called update Visibility if needed

2022-03-07 13:20 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/galleryContainer.js
> +   const { container } = this.props;
I dont want free floating logic in general lifecycle functions

2022-03-09 08:26 UTC, merged