Slideshow virtualization
wix-incubator/pro-gallery pull request #780
Opened 2022-03-13 15:28 UTC by shmuelhizmi

2022-03-13 15:31 UTC, nirnaor requested changes
1. Description of what your PR is doing
2. Tests for new logic
3. No formatting changes in PRS

2022-03-13 15:32 UTC, yhattav requested changes
remove lint changes

2022-03-14 13:12 UTC, nirnaor requested changes

2022-03-14 13:12 UTC, nirnaor commented on packages/gallery/package.json
> +    "test:spec": "jest --testPathPattern='.*/components/.*.spec.js'",
remove

2022-03-14 13:12 UTC, nirnaor commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +    const groups = this.props.getVisibleItems(galleryGroups, container);
remove `this` dependency

2022-03-14 13:12 UTC, nirnaor commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +    }
remove from component

2022-03-15 08:59 UTC, nirnaor requested changes

2022-03-15 08:59 UTC, nirnaor commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +    const groups = this.props.getVisibleItems(galleryGroups, container);
[question]
Why didn't you destruct the `getVisibleItems and galleryContainerRef` from `this.props` like you did with `options`

2022-03-15 08:59 UTC, nirnaor commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +                  shouldRenderEmpty: !shouldRender,
[question]
You could have simply returned only the `shouldRender`ed groups and then you could remove the ternary (`:` operator). What do you think?

2022-03-15 08:59 UTC, nirnaor commented on packages/gallery/src/components/helpers/slideshowVirtualization.ts
> +  } = options.behaviourParams?.gallery?.horizontal?.itemVirtualization || {};
@yhattav is it necessary to check all the `?` stuff? Aren't we assuring new SP will always be present?

2022-03-15 08:59 UTC, nirnaor commented on packages/gallery/src/components/helpers/slideshowVirtualization.ts
> +        return { group, shouldRender: false };
Lines 40 - 43 and lines 46- 49 are duplicated. Can you try and reuse?

2022-03-15 08:59 UTC, nirnaor commented on packages/gallery/tests/components/gallery/slideshowView.spec.js
> +        },
Please don't duplicate tests and change something small. I can't understand the difference between the tests without reading it slowly. The difference between tests should be understood from the code, not from the `it`

2022-03-15 08:59 UTC, nirnaor commented on packages/lib/src/common/utils/index.js
> +  awaitStateChange(that, state) {
Why did you add a method that no one is using?

2022-03-24 09:32 UTC, nirnaor requested changes
Please attach:

1. Passing canary 
2. Using that canary - url to the site containing the bug solved

2022-03-24 09:32 UTC, nirnaor commented on packages/lib/src/common/utils/index.js
> +
remove

2022-03-24 09:32 UTC, nirnaor commented on packages/gallery/src/components/helpers/virtualization.ts
> +  const size = isHorizontal ? galleryWidth : galleryHeight;
nice

2022-03-24 09:32 UTC, nirnaor commented on packages/lib/src/common/interfaces/virtualization.ts
> +  forwardItemMargin?: number;
[question]
how will your code work when all these items are `null`? Why are they optional

2022-03-27 08:21 UTC, merged