mouse cursor wip
wix-incubator/pro-gallery pull request #882
Opened 2022-07-03 12:02 UTC by yuvalab

2022-08-04 12:16 UTC, yuvalab commented on packages/lib/src/settings/options/index.js
>  // TODO = add the options:
options.ts - inteface adding the option

2022-08-04 12:23 UTC, yuvalab commented on packages/lib/src/settings/options/index.js
>  // TODO = add the options:
change and import the right name of the sp

2022-08-17 09:41 UTC, yhattav requested changes

2022-08-17 09:41 UTC, yhattav commented on packages/gallery/src/components/helpers/mouseCursorPosition.js
> +const throttle = (func, time) => {
find and use utils.throttle. if it doesnt exist create it and use it. this is very generic

2022-08-17 09:41 UTC, yhattav commented on packages/gallery/src/components/helpers/mouseCursorPosition.js
> +  console.log(position);
remove log

2022-08-17 09:41 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +    const mouseCursorEnabled = arrowsPosition === 2;
use CONST. change the naming of the character.

2022-08-17 09:41 UTC, yhattav commented on packages/gallery/src/components/helpers/mouseCursorPosition.js
> +const throttle = (func, time) => {
use utils or create throttle in the utils to be commonly used

2022-08-17 09:41 UTC, yhattav commented on packages/gallery/src/components/helpers/renderCursorController.js
> +export function renderArrowButton({
why is this related to cursor controller (i.e why in this file and not an arrow related file?

2022-08-22 08:17 UTC, closed without merging