reuse button
wix-incubator/pro-gallery pull request #902
Opened 2022-08-03 12:50 UTC by yuvalab

2022-08-04 11:54 UTC, yuvalab commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> +    const renderButtonArrow = (directionIsLeft) => {
renderArrowButton

2022-08-08 14:13 UTC, yhattav requested changes

2022-08-08 14:13 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> -            (utils.isMobile() ? ' pro-gallery-mobile-indicator' : '')
In Master only the left arrow has this class. Im not sure why but the change you make places this class on right and left

2022-08-08 14:13 UTC, yhattav commented on packages/gallery/src/components/gallery/proGallery/slideshowView.js
> -            (utils.isMobile() ? ' pro-gallery-mobile-indicator' : '')
try to figure out what this class is. It looks like someone just missed adding it on the other arrow (added it only once).

2022-08-09 12:30 UTC, yhattav approved these changes

2022-08-10 07:40 UTC, merged