version 5 beta
wix-incubator/pro-gallery pull request #984
Opened 2022-11-09 14:30 UTC by yhattav

2022-11-09 14:31 UTC, nirnaor requested changes
You will also need package json changes in order for the version to start bumping correctly.

2022-11-09 14:35 UTC, yhattav commented
> You will also need package json changes in order for the version to start bumping correctly.

can you explain? should I bump all versions to 5.0.0 in the different packages?

2022-11-10 08:07 UTC, nirnaor approved these changes

2022-11-10 08:53 UTC, nirnaor requested changes
Just to be extra cautious I would change the external packages version to be beta also

2024-08-19 10:33 UTC, closed without merging